services:
  db:
    image: mysql:8.0
    container_name: mysql_db_prod
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME:-myuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mypassword}
    volumes:
      - db_data_prod:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password

  backend:
    image: ${DOCKERHUB_USERNAME}/tutor-backend:latest
    container_name: spring_backend_prod
    restart: always
    mem_limit: 512m
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?rewriteBatchedStatements=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Sắp tới nếu dùng user riêng, nên là MYSQL_PASSWORD
      APP_INIT-DATA_ENABLED: "true"
      SPRING_PROFILES_ACTIVE: prod
      # Giới hạn RAM cho JVM để chạy ổn trên VPS 1GB RAM
      JAVA_OPTS: ${JAVA_OPTS:-"-Xms180m -Xmx256m"}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}

  frontend:
    image: ${DOCKERHUB_USERNAME}/tutor-frontend:latest
    container_name: nextjs_frontend_prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      # URL Backend API khi được gọi từ trình duyệt. Ở Production, API phải trỏ đến Domain (VD: https://api.tutor.com)
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend

volumes:
  db_data_prod:
