services:
  db:
    image: mysql:8.0
    container_name: mysql_db_prod
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME:-myuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mypassword}
    volumes:
      - db_data_prod:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - tutor-network

  backend:
    image: ${DOCKERHUB_USERNAME}/tutor-backend:latest
    container_name: spring_backend_prod
    restart: always
    mem_limit: 1024m # Container Backend được cấp trần 1GB RAM
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?rewriteBatchedStatements=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Sắp tới nếu dùng user riêng, nên là MYSQL_PASSWORD
      APP_INIT_DATA_ENABLED: ${INIT_DATA_ENABLED:-true}
      SPRING_PROFILES_ACTIVE: prod
      # Cấu hình bung lụa trên VPS 4GB RAM: Cache cực lớn, CPU rảnh rang 
      JAVA_OPTS: ${JAVA_OPTS:--Xms256m -Xmx768m -XX:+UseG1GC -XX:MaxMetaspaceSize=256m}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      APP_JWT_SECRET: ${APP_JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
    networks:
      - tutor-network

  frontend:
    image: ${DOCKERHUB_USERNAME}/tutor-frontend:latest
    container_name: nextjs_frontend_prod
    restart: always
    ports:
      - "3000:3000"
    environment:
      # URL Backend API khi được gọi từ trình duyệt. Ở Production, API phải trỏ đến Domain (VD: https://api.tutor.com)
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    depends_on:
      - backend
    networks:
      - tutor-network

networks:
  tutor-network:
    driver: bridge

volumes:
  db_data_prod:
